name: CI

on:
  push:
    branches: [ "develop", "test1" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  my_version: ${{vars.MYVERMAJOR}}.${{vars.MYVERMINOR}}.${{github.run_number}}.${{github.run_attempt}}
  
jobs:
  printVersion:
    runs-on: ubuntu-latest
    steps:
    - name: Print version
      run: echo ${{env.my_version}}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{env.my_version}}
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Publish to folder
      run: dotnet publish /WebMinimalApi/WebMinimalApi.csproj -p:PublishProfile=GitHubPublish -p:Version=${{env.my_version}}
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapi
        path: publish/WebMinimalApi/
#    - name: Publish to folder
#      uses: wangyucode/sftp-upload-action@v2.0.2
#      with:
#        host: ${{secrets.sftphost}}
#        port: ${{secrets.sftpport}}
#        username: ${{secrets.sftpuser}}
#        password: ${{secrets.sftpassword}}
#        localDir: publish/WebMinimalApi/
#        remoteDir: /BuildArtefacts/${{env.my_version}}/WebMinimalApi
